### ISSUE TITLE
Release on CurseForge and Modrinth

### ISSUE THREAD

**Issue by UrBoiTom** [ferriarnus/mixy#10]
Release on CurseForge and Modrinth. If it is too buggy add progress reports or something similar here.

**Comment by ferriarnus** [comment]
Unfortunately no. Even if I were to disregard the buggyness and other issue that come from more actively supporting it, I legally can not release this port. It is based on [voxy](https://github.com/MCRcortex/voxy), which is licensed "All Rights Reserved". As such, I am not allowed to release it on CF or MR without explicit permission of cortex.

**Comment by UrBoiTom** [comment]
> Without explicit permission of cortex

Could you not ask her for permission?

**Comment by ferriarnus** [comment]
Yes, but at this point I do not plan to.
