### ISSUE TITLE
Crashing when entering the world

### ISSUE THREAD

**Issue by Sharkow1743** [ferriarnus/mixy#9]
Mods:
embeddium-0.3.28+mc1.20.1
mixy-0.1.5-alpha

Error:
java.lang.ClassCastException: class org.joml.FrustumIntersection cannot be cast to class me.cortex.voxy.client.mixin.joml.AccessFrustumIntersection (org.joml.FrustumIntersection is in module org.joml@1.10.5 of loader 'MC-BOOTSTRAP' @7e9131d5; me.cortex.voxy.client.mixin.joml.AccessFrustumIntersection is in module mixy@0.1.5-alpha of loader 'TRANSFORMER' @55fdf7f9)

[latest.log](https://github.com/user-attachments/files/16492725/latest.log)

**Comment by ferriarnus** [comment]
Oh, this was an issue already on 1.20.1? Guess nobody with a non-nvidia card used it... I'll try to push a fix to 1.20.1 as well.

**Comment by Sharkow1743** [comment]
But I have an nvidia video card

**Comment by ferriarnus** [comment]
Oh? Then are you using the non-nividia render setting? Since that one is the cause of this.

**Comment by Sharkow1743** [comment]
Idk. Where is the non-nividia render setting?

**Comment by ferriarnus** [comment]
Go to "mods", search mixy and press config. It should be one of the last settings which currenly will be off.

**Comment by Sharkow1743** [comment]
When I click "Mixy" in "Mods" an error occurs: java.lang.NoClassDefFoundError: me/shedaniel/clothconfig2/api/AbstractConfigListEntry

[latest.log](https://github.com/user-attachments/files/16493907/latest.log)

**Comment by ferriarnus** [comment]
You need to have clothconfig installed yes, forgot to mention that.

**Comment by Sharkow1743** [comment]
Last setting is on but still chrashing

**Comment by ferriarnus** [comment]
Then in the f3 menu, which gpu is being used?

**Comment by Sharkow1743** [comment]
nvidia geforce mx 110

**Comment by ferriarnus** [comment]
Right that one can't use the nvidia path. I know the issue and I'll get it fixed hopefully soon.

**Comment by Sharkow1743** [comment]
I think this mod is abandoned
